// SESSION ACTION TYPES
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

// USER ACTION TYPES
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE'
export const FETCH_USER_STARTUP_NAME = 'FETCH_USER_STARTUP_NAME'
export const FETCH_ALL_USER_DATA = 'FETCH_ALL_USER_DATA'

// PROJECT ACTION TYPES
export const FETCH_ALL_PROJECTS = 'FETCH_ALL_PROJECTS'
export const FETCH_PROJECT = 'FETCH_PROJECT'
