// SESSION ACTION TYPES
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

// USER ACTION TYPES
export const CREATE_ACCOUNT_FAILURE = 'CREATE_ACCOUNT_FAILURE'
